# Generated by Django 3.1.6 on 2021-02-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorual',
            new_name='Tutorial',
        ),
    ]
